AWSTemplateFormatVersion: '2010-09-09'
Description: The AWS CloudFormation Template for Initializing Static Sites Pipeline

Parameters:
  Region:
    Type: String
    Default: us-east-1
  TimeStamp:
    Type: String
  AccountId:
    Type: String
    Default: '{{resolve:ssm:account-id:1}}'
  LambdasBucketName:
    Type: String
    Default: '{{resolve:ssm:cloudformation-monitor-lambdas-bucket:1}}'
  SlackWebHookPath:
    Type: String
    Default: '{{resolve:secretsmanager:slack-webhook-paths:SecretString:static-sites-pipeline:1}}'

Resources:

# Buckets

  LambdasBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LambdasBucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  LatestTimeStamp:
    Value: !Ref TimeStamp